
#define DEVICE_ID 1
//
#define MAIL_SZ_EXACTO_COMMANDER 16
#define GETT_ID_CNT_EXACTO_COMMANDER 3
#define MAIL_ID_CNT_EXACTO_COMMANDER 3

#define THREAD_CONTROL_BUFFER_SZ 16
#define THREAD_CONTROL_CNT 6

#define SPI_PACK_SZ 16
